services:
  nextjs:
    build:
      context: nextjs
    ports:
      - 3000:3000
    volumes:
      - ./nextjs:/nextjs
    command: npm run dev
    networks:
      - mercari-app-network

networks:
  mercari-app-network:
    driver: bridge